#!/usr/bin/env python3
"""
Convert a MIDI file to a C header for MidiPlayer library.

Outputs mp_note_event_t / mp_track_t / mp_score_t structures
compatible with source/mp_sequencer.h.

Usage:
    python3 midi_to_header.py input.mid output.h [--max-tracks N] [--name SCORE_NAME]
"""

import mido
import argparse
import math
import sys

SAMPLE_RATE = 16000


def midi_note_to_phase_inc(note):
    """Convert MIDI note number to phase increment for 16kHz sample rate."""
    if note < 24 or note > 108:
        return 0
    freq = 440.0 * (2.0 ** ((note - 69) / 12.0))
    return round(freq * 65536 / SAMPLE_RATE)


def parse_midi(filename, max_tracks):
    mid = mido.MidiFile(filename)
    tracks = []

    for track in mid.tracks:
        events = []
        current_time = 0.0
        tempo = 500000  # default 120 BPM
        note_on_times = {}
        note_on_velocities = {}

        for msg in track:
            delta_time = mido.tick2second(msg.time, mid.ticks_per_beat, tempo)
            current_time += delta_time

            if msg.type == 'set_tempo':
                tempo = msg.tempo
                continue

            if msg.type == 'note_on' and msg.velocity > 0:
                note_on_times[msg.note] = current_time
                note_on_velocities[msg.note] = msg.velocity
                continue

            if msg.type == 'note_off' or (msg.type == 'note_on' and msg.velocity == 0):
                if msg.note in note_on_times:
                    start_time = note_on_times[msg.note]
                    duration_ms = int((current_time - start_time) * 1000)
                    start_ms = int(start_time * 1000)
                    phase_inc = midi_note_to_phase_inc(msg.note)
                    # Scale velocity from 0-127 to 0-127 (already in range)
                    volume = min(note_on_velocities[msg.note], 127)

                    if phase_inc > 0 and duration_ms > 0:
                        events.append((start_ms, phase_inc, duration_ms, volume))

                    del note_on_times[msg.note]
                    del note_on_velocities[msg.note]

        if events:
            # Sort by start time
            events.sort(key=lambda e: e[0])
            tracks.append(events)

    # Limit tracks
    if len(tracks) > max_tracks:
        # Keep the tracks with most notes
        tracks.sort(key=lambda t: len(t), reverse=True)
        tracks = tracks[:max_tracks]

    return tracks


def assign_channels(tracks):
    """
    Assign oscillator channels to note events.
    Each track gets a base channel. When a track has simultaneous notes
    (polyphony), extra notes spill into higher channels.
    """
    max_ch = 3  # channels 0-2 for square waves, 3 is noise

    for track_idx, events in enumerate(tracks):
        base_ch = track_idx % (max_ch + 1)
        # Track active notes: channel -> off_time
        active = {}

        for i, (start_ms, phase_inc, duration_ms, volume) in enumerate(events):
            # Find a free channel
            assigned_ch = base_ch
            # Release expired notes
            expired = [ch for ch, off in active.items() if off <= start_ms]
            for ch in expired:
                del active[ch]

            # If base channel is busy, try others
            if base_ch in active:
                for ch in range(max_ch + 1):
                    if ch not in active:
                        assigned_ch = ch
                        break
                else:
                    # All channels busy, steal base channel
                    assigned_ch = base_ch

            active[assigned_ch] = start_ms + duration_ms
            events[i] = (start_ms, phase_inc, duration_ms, volume, assigned_ch)


def generate_header(tracks, output_file, score_name):
    with open(output_file, 'w') as f:
        f.write("/*\n")
        f.write(f" * Auto-generated by midi_to_header.py\n")
        f.write(f" * Score: {score_name}\n")
        f.write(" */\n")
        f.write("#ifndef MIDI_DATA_H\n")
        f.write("#define MIDI_DATA_H\n\n")
        f.write("#include \"mp_sequencer.h\"\n\n")

        total_events = 0

        for i, events in enumerate(tracks):
            f.write(f"static const mp_note_event_t {score_name}_track{i}[] = {{\n")
            for (start_ms, phase_inc, duration_ms, volume, channel) in events:
                f.write(f"    {{ .start_time_ms = {start_ms}, "
                        f".phase_inc = {phase_inc}, "
                        f".duration_ms = {duration_ms}, "
                        f".volume = {volume}, "
                        f".channel = {channel} }},\n")
                total_events += 1
            f.write("};\n\n")

        f.write(f"static const mp_track_t {score_name}_tracks[] = {{\n")
        for i, events in enumerate(tracks):
            f.write(f"    {{ .events = {score_name}_track{i}, "
                    f".event_count = sizeof({score_name}_track{i}) "
                    f"/ sizeof({score_name}_track{i}[0]) }},\n")
        f.write("};\n\n")

        f.write(f"static const mp_score_t {score_name} = {{\n")
        f.write(f"    .tracks = {score_name}_tracks,\n")
        f.write(f"    .track_count = sizeof({score_name}_tracks) "
                f"/ sizeof({score_name}_tracks[0]),\n")
        f.write("};\n\n")
        f.write("#endif /* MIDI_DATA_H */\n")

        # Size estimate: 12 bytes per event (struct with padding)
        size_kb = total_events * 12 / 1024
        print(f"Generated: {output_file}")
        print(f"  Tracks: {len(tracks)}")
        print(f"  Total events: {total_events}")
        print(f"  Estimated Flash: {size_kb:.1f} KB")


def main():
    parser = argparse.ArgumentParser(description="Convert MIDI to MidiPlayer C header")
    parser.add_argument('input', help='Input MIDI file')
    parser.add_argument('output', help='Output .h file')
    parser.add_argument('--max-tracks', type=int, default=3, help='Max tracks (default: 3)')
    parser.add_argument('--name', default='midi_score', help='Score variable name')
    args = parser.parse_args()

    tracks = parse_midi(args.input, args.max_tracks)
    if not tracks:
        print("Error: No note events found in MIDI file", file=sys.stderr)
        sys.exit(1)

    assign_channels(tracks)
    generate_header(tracks, args.output, args.name)


if __name__ == '__main__':
    main()
